#!/bin/bash
# Changes current directory to project folder in order to be able to
# run the tool from any folder
cd $(dirname $0)

# Define PythonPath with AST node folders, visitors and vulnerabilities definitions
export PYTHONPATH=AST/:AST/visitors/:vuln/

#Run the tool with Python3 with parameters given by the user
python3 tool.py $1 $2
